FROM node:16
WORKDIR /home/eaglerserverlist/backend/
COPY package*.json ./
RUN npm ci --only=production
COPY . .
EXPOSE 3002
RUN npx tsc
WORKDIR /home/eaglerserverlist/backend/dist/
CMD ["node", "index.js"]
